global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'besu-Cloud'
    static_configs:
      - targets: ['10.239.152.40:9545']

  - job_name: 'besu-Fog1_Jetson@20W'
    static_configs:
      - targets: ['10.239.151.140:9546']

  - job_name: 'besu-Fog2_Jetson@20W'
    static_configs:
      - targets: ['10.239.145.144:9547']

  - job_name: 'besu-Edge1_Jetson@10W'
    static_configs:
      - targets: ['10.239.150.252:9548']

  - job_name: 'besu-Edge2_RapsberryPi4B'
    static_configs:
      - targets: ['10.239.148.15:9549']

  - job_name: 'besu-Edge3_RapsberryPi4B'
    static_configs:
      - targets: ['10.239.149.202:9550']

  # - job_name: 'system-metrics-cloud'
  #   static_configs:
  #     - targets: ['localhost:9100']


