global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'besu-cloud'
    static_configs:
      - targets: ['localhost:9545']

  - job_name: 'besu-fog'
    static_configs:
      - targets: ['localhost:9546']

  - job_name: 'besu-edge'
    static_configs:
      - targets: ['localhost:9547']

  - job_name: 'system-metrics-cloud'
    static_configs:
      - targets: ['localhost:9100']


